version: '3.3'

services:
  api:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0 --port=80
    ports:
      - "5050:80"
    environment:
      - FLASK_APP=main.py
    volumes:
      - .:/app
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    container_name: flask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=flaskuser
      - POSTGRES_DB=flaskdb

volumes:
  postgres_data: